code --install-extension bajdzis.vscode-twig-pack
code --install-extension dssiqueira.drupal-8-snippets
code --install-extension ecmel.vscode-html-css
code --install-extension esbenp.prettier-vscode
code --install-extension GitHub.vscode-pull-request-github
code --install-extension hashicorp.terraform
code --install-extension HookyQR.beautify
code --install-extension liximomo.sftp
code --install-extension MehediDracula.php-namespace-resolver
code --install-extension ms-azuretools.vscode-docker
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.jupyter
code --install-extension ms-toolsai.jupyter-keymap
code --install-extension ms-toolsai.jupyter-renderers
code --install-extension ms-vscode-remote.remote-containers
code --install-extension ritwickdey.LiveServer
code --install-extension tomoki1207.pdf
code --install-extension whatwedo.twig
